import Footer from '@/components/Footer/Footer'
import Navbar from '@/components/Navbar/Navbar'
import React from 'react'

const index = () => {
    return (
        <div className='max-w-screen font-poppins items-center justify-center '>
            <Navbar />
            <div className='max-w-6xl mx-auto flex  my-4 flex-col justify-center items-center'>
                <h1 className='text-4xl  text-center uppercase font-semibold'>privacy & policy</h1>
                <div className=' p-4 my-2  mx-auto justify-center item-center flex flex-col'>
                    <p className='my-2 break-normal'>
                        TOKERE ENERGY SOLUTIONS PRIVATE LIMITED is in the business to provide a blockchain platform trading for Renewable Energy Certificates, Carbon credits and other similar Environment Attributable Certificates by tokenizing and fractionalizing them to enable Real estate developers & Operators, Industries, MSMEs, Residential households, etc., to consume and progress their Net ‘0’ targets. TOKERE ENERGY SOLUTIONS PRIVATE LIMITED based in Bangalore, Karnataka. Our Privacy Policy is incorporated as part of the <a href='www.tokere.co'>tokere.co</a> Terms of use. Please read this Privacy Policy and our Terms & Conditions carefully before using our Services. By using TOKERE ENERGY SOLUTIONS PRIVATE LIMITED services, you agree to the provisions of this Privacy Policy.
                        We take the individual&apos;s privacy interests very seriously, whose information we receive throughout our services. We provide this Privacy Policy to describe how we use and maintain the information collected through our services and what benefits users have to control how their information is used and shared.

                    </p>
                    <ul>
                        
                        <li className='my-2'>
                            <h1 className='font-bold text-xl'>1. GENERAL</h1>
                            <ul className='px-8 my-2'>
                                <li className='my-2'><span className='font-bold'>a)</span> This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.</li>
                                
                                <li className='my-2'><span className='font-bold'>b)</span> This document is published in accordance with the provisions of Rule 4 (1) of the Information Technology (Reasonable Security Practices and Procedures and sensitive personal data or information) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of TOKERE ENERGY SOLUTIONS PRIVATE LIMITED.</li>
                                
                                <li className='my-2'><span className='font-bold'>c)</span> The domain name https://www.tokere.co is owned and operated by TOKERE ENERGY SOLUTIONS  PRIVATE LIMITED having its registered office at 17B HABITAT CREST, ITPL ROAD,  WHITEFIELD, RAJAPALYA, MAHADEVAPURA, KARNATAKA INDIA -560048.</li>
                                
                                <li className='my-2'><span className='font-bold'>d)</span> This Privacy Policy is effective from the date and time the user registers with TOKERE ENERGY SOLUTIONS PRIVATE LIMITED by filling up the details and accepting the terms & conditions laid out in the Site Policy.</li>
                            </ul>
                        </li>

                        <li className='my-2'>
                            <h1 className='font-bold text-xl'>2. COLLECTION OF PERSONAL AND OTHER INFORMATION</h1>
                            <ul className='px-8 my-2'>
                                <li className='my-2'><span className='font-bold'>a)</span> To provide its customers a personalized browsing experience, TOKERE may collect personal information from you. Additionally, the website may require you to complete a registration form or seek some information from you.</li>
                                
                                <li className='my-2'><span className='font-bold'>b)</span> The User is aware that the Company/Website may automatically track certain information about the User based upon the User&apos;s IP address and the User&apos;s behaviour on the Website, and the User expressly consents to the same. The User is aware that this information is used to do internal research on user demographics, interests, and behaviour, enable the Company/Website to understand better, and cater to the interests of its users. The User is expressly made aware that such information may include the URL that the User visited prior to accessing the Website, the URL which the User subsequently visits (whether or not these URLs form a part of the Website), the User&apos;s computer & web browser information, the User&apos;s IP address, etc.</li>
                                
                                <li className='my-2'><span className='font-bold'>c)</span> The User is further aware that the Company/Website may occasionally request the User to write reviews for products/services purchased/availed of by the User from the Website and reviews for the various sellers listing their products/services on the Website. The User is aware that such reviews will help other users of the website make prudent and correct purchases, and also help the Company/Website remove sellers whose products are unsatisfactory in any way. The User hereby expressly authorizes the Company/Website to publish any or all reviews written by the User on the Website, along with the User&apos;s name and specific contact details, for the benefit and use of other Users of the Website.</li>
                            </ul>
                        </li>

                        <li className='my-2'>
                            <h1 className='font-bold text-xl'>3. COOKIES</h1>
                            <ul className='px-8'>
                                <li className='my-2'><span className='font-bold'>a)</span> The User is aware that a &apos;Cookie&apos; is a small piece of information stored by a web server on a web browser so it can later be traced back from that particular browser and that cookies are useful for enabling the browser to remember information specific to a given user, including but not limited to a User&apos;s login identification, password, etc. The User is aware that the Website places permanent and temporary cookies in the User&apos;s computer&apos;s hard drive and web browser and does hereby expressly consent to the same.</li>
                                
                                <li className='my-2'><span className='font-bold'>b)</span> The User is further aware that the Website uses data collection devices such as cookies on certain pages of the Website to help analyze web page flow, measure promotional effectiveness, and promote trust and safety, and that certain features of the Website are only available through the use of such cookies. While the User is free to decline the Website&apos;s cookies if the User&apos;s browser permits, the User may consequently be unable to use certain features on the Website.</li>
                            </ul>
                        </li>

                        <li className='my-2'>
                            <h1 className='font-bold text-xl'>4. DIVULGING/SHARING OF PERSONAL INFORMATION</h1>
                            <ul className='px-8 my-2'>
                                <li className='my-2'><span className='font-bold'>a)</span> The User is aware that the TOKERE ENERGY SOLUTIONS PRIVATE LIMITED may share the User&apos;s personal information with other corporate entities and affiliates to help detect and prevent identity theft, fraud, and other potentially illegal acts; correlate related or multiple accounts to prevent abuse of the Website&apos;s services; and to facilitate joint or co-branded services, where such services are provided by more than one corporate entity.</li>
                                
                                <li className='my-2'><span className='font-bold'>b)</span> The User is aware that the TOKERE ENERGY SOLUTIONS PRIVATE LIMITED may disclose personal information if required to do so by law or if the DASV Company in good faith believes that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal processes. The TOKERE ENERGY SOLUTIONS PRIVATE LIMITED may also disclose the User&apos;s personal information to law enforcement offices, third party rights owners, or other third parties if it believes that such disclosure is reasonably necessary to enforce the Terms or Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of its users, or the general public.</li>
                            </ul>
                        </li>

                        <li className='my-2'>
                            <h1 className='font-bold text-xl'>5. SECURITY</h1>
                            <p className='px-8 my-2'> Transactions on the Website are secure and protected. Any information entered by the User when transacting on the Website is encrypted to protect the User against unintentional disclosure to third parties. The User&apos;s credit and debit card information is not received, stored by, or retained by the TOKERE ENERGY SOLUTIONS PRIVATE LIMITED in any manner. This information is supplied by the User directly to the relevant payment gateway, which is authorized to handle the information provided and is compliant with the regulations and requirements of various banks and institutions, and payment franchisees that it is associated with.</p>
                        </li>

                        <li className='my-2'>
                            <h1 className='font-bold text-xl'>6. DISPUTE RESOLUTION AND JURISDICTION</h1>
                            <p className='px-8 my-2'> It is expressly agreed to by the Parties hereto that the formation, interpretation and performance of this Policy and any disputes arising here from will be resolved through a two-step Alternate Dispute Resolution (&quot;ADR&quot;) mechanism. It is further agreed to by the Parties that the contents of this Section shall survive even after the termination or expiry of the Policy and/or Terms.</p>
                            <br />
                            <ul className='px-8 my-2'>
                                <li className='my-2'><span className='font-bold'>a) Mediation:</span> In case of any dispute between the parties, the Parties will attempt to resolve the same amicably amongst themselves, to the mutual satisfaction of both Parties. In the event that the Parties are unable to reach such an amicable solution within thirty (30) days of one Party communicating the existence of a dispute to the other Party, the dispute will be resolved by arbitration, as detailed herein below.</li>
                                
                                <li className='my-2'><span className='font-bold'>b) Arbitration:</span> In the event that the Parties are unable to amicably resolve a dispute by mediation, said dispute will be referred to arbitration by a sole arbitrator to be appointed by the TOKERE ENERGY SOLUTIONS PRIVATE LIMITED, and the award passed by such sole arbitrator will be valid and binding on both Parties. The Parties shall bear their own costs for the proceedings, although the sole arbitrator may, in his/her sole discretion, direct either Party to bear the entire cost of the proceedings. The arbitration shall be conducted in English, and the seat of Arbitration shall be at Bangalore, Karnataka.</li>
                            </ul>
                            <p className='px-8 my-2'>The Parties expressly agree that the Terms, Policy, and any other agreements entered into between the Parties are governed by the laws, rules, and regulations of India and that the Courts at Bangalore, Karnataka shall have exclusive jurisdiction over any disputes arising between the Parties.</p>
                        </li>
                    </ul>
                </div>
            </div>
            <Footer />
        </div>
    ) 
}

export default index